EntertainmentLists/EntertainmentLists/Pages/AwaitingFilms/AwaitingAdd.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EntertainmentLists.DAL.Interfaces;
using EntertamentLists.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EntertainmentLists.Pages.AwaitingFilms
{
    public class AwaitingAddModel : PageModel
    {
        private readonly IFilmService<AwaitingFilm> _awaitingFilmService;
        [BindProperty]
        public AwaitingFilm AwaitingFilm { get; set; }
        public AwaitingAddModel(IFilmService<AwaitingFilm> awaitingFilmService)
        {
            _awaitingFilmService = awaitingFilmService;
        }
        public IEnumerable<AwaitingFilm> awaitingFilmModels { get; set; }
        public void OnGet()
        {
            awaitingFilmModels = _awaitingFilmService.GetAllFilmsFromDb();
        }
        public IActionResult OnPost()
        {
            _awaitingFilmService.SaveNewFilmToDb(AwaitingFilm);
            return RedirectToPage("/AwaitingFilms/AwaitingFilmRazor");
        }
    }
}

EntertainmentLists/EntertainmentLists/Pages/AwaitingFilms/AwaitingEdit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EntertainmentLists.DAL.Interfaces;
using EntertamentLists.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EntertainmentLists.Pages.AwaitingFilms
{
    public class AwaitingEditModel : PageModel
    {
        private readonly IFilmService<AwaitingFilm> _awaitingFilmService;
        public IEnumerable<AwaitingFilm> awaitingFilmModels { get; set; }
        public AwaitingEditModel(IFilmService<AwaitingFilm> awaitingFilmService)
        {
            _awaitingFilmService = awaitingFilmService;
        }
        public void OnGet()
        {
            awaitingFilmModels = _awaitingFilmService.GetAllFilmsFromDb();
        }
        public IActionResult OnPost(AwaitingFilm awaitingFilm)
        {
            _awaitingFilmService.ChangeFilmPropertiesInDb(awaitingFilm);
            return RedirectToPage("/AwaitingFilms/AwaitingFilmRazor");
        }
    }
}

EntertainmentLists/EntertainmentLists/Pages/AwaitingFilms/AwaitingFilmRazor.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EntertainmentLists.DAL.Interfaces;
using EntertamentLists.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EntertainmentLists.Pages.AwaitingFilms
{
    public class AwaitingFilmRazorModel : PageModel
    {
        private readonly IFilmService<AwaitingFilm> _awaitingFilmService;
        public AwaitingFilmRazorModel(IFilmService<AwaitingFilm> awaitingFilmService)
        {
            _awaitingFilmService = awaitingFilmService;
        }
        public IEnumerable<AwaitingFilm> awaitingFilmModels { get; set; }
        public void OnGet()
        {
            awaitingFilmModels = _awaitingFilmService.GetAllFilmsFromDb();
        }
        public IActionResult OnPostDelete(int id)
        {
            _awaitingFilmService.RemoveFilmFromDb(id);
            return RedirectToPage();
        }
    }
}

EntertainmentLists/EntertainmentLists/Pages/AwaitingFilms/AwaitingAdd.cshtml
@page
@model EntertainmentLists.Pages.AwaitingFilms.AwaitingAddModel
@{
    var nextId = Model.awaitingFilmModels.Count() + 1;
    var i = 1;
}

<style>
    #add {
        margin-top: 20px;
        margin-bottom: 20px;
    }

    #filmName {
        min-width: 800px;
        max-width: 800px;
        word-wrap: break-word;
        text-align: center;
    }
</style>

<h1>Хочу посмотреть</h1>
<form method="post">
    <button type="submit" id="add" class="btn btn-success btn-lg">Сохранить</button>
    <div>
        <table>
            <tr>
                <th>№</th>
                <th id="filmName">Название</th>
            </tr>
            <tr>
                <td><input asp-for="AwaitingFilm.Id" type="hidden" /></td>
                <td id="filmName"><input asp-for="AwaitingFilm.Name" placeholder="Название" /></td>
            </tr>

            @if (Model.awaitingFilmModels != null)
            {
                @foreach (var awaitingFilm in Model.awaitingFilmModels)
                {
                    <tr>
                        <td>
                            @(i++)
                        </td>
                        <td id="filmName">
                            @awaitingFilm.Name
                            <hr />
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</form>

EntertainmentLists/EntertainmentLists/Pages/AwaitingFilms/AwaitingEdit.cshtml
@page "{id}:int"
@model EntertainmentLists.Pages.AwaitingFilms.AwaitingEditModel
@{
    var updatingAwaitingFilm = RouteData.Values["id"].ToString();
    var i = 1;
}

<style>
    table {
        margin-top: 95px;
    }

    #filmName {
        min-width: 800px;
        max-width: 800px;
        word-wrap: break-word;
        text-align: center;
    }
</style>

<h1>Хочу посмотреть</h1>
<form method="post">
    <div>
        <table>
            <tr>
                <th>№</th>
                <th id="filmName">Название</th>
            </tr>

            @if (Model.awaitingFilmModels != null)
            {
                @foreach (var awaitingFilm in Model.awaitingFilmModels)
                {
                    <tr>
                        @if (awaitingFilm.Id == int.Parse(updatingAwaitingFilm))
                        {
                            <td>
                                @(i++)
                                <input asp-for="@awaitingFilm.Id" type="hidden" />
                            </td>
                            <td id="filmName">
                                <input asp-for="@awaitingFilm.Name" />
                                <hr />
                            </td>
                        }
                        else
                        {
                            <td>
                                @(i++)
                            </td>
                            <td id="filmName">
                                @awaitingFilm.Name
                                <hr />
                            </td>
                        }
                        <td>
                            <button type="submit" class="btn btn-warning btn-sm">Сохранить</button>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</form>

EntertainmentLists/EntertainmentLists/Pages/AwaitingFilms/AwaitingFilmRazor.cshtml
@page
@model EntertainmentLists.Pages.AwaitingFilms.AwaitingFilmRazorModel
@{
    var i = 1;
}

<style>
    #add {
        margin-top: 20px;
        margin-bottom: 20px;
    }

    #filmName {
        min-width: 800px;
        max-width: 800px;
        word-wrap: break-word;
        text-align: center;
    }
</style>

<h1>Хочу посмотреть</h1>
<form method="post">
    <a asp-page="/AwaitingFilms/AwaitingAdd" type="button" id="add" class="btn btn-success btn-lg">Добавить</a>
    <div>
        <table>
            <tr>
                <th>№</th>
                <th id="filmName">Название</th>
            </tr>
            @if (Model.awaitingFilmModels != null)
            {
                @foreach (var awaitingFilm in Model.awaitingFilmModels)
                {
                    <tr>
                        <td>
                            @(i++)
                        </td>
                        <td id="filmName">
                            @awaitingFilm.Name
                            <hr />
                        </td>
                        <td>
                            <a asp-page="/AwaitingFilms/AwaitingEdit" asp-route-id="@awaitingFilm.Id" type="button" class="btn btn-warning btn-sm">Редактировать</a>
                        </td>
                        <td>
                            <button type="submit" asp-page-handler="delete" asp-route-id="@awaitingFilm.Id" class="btn btn-danger btn-sm">Удалить</button>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</form>